### PR TITLE
Update database.db with Anniversary content

### PR DESCRIPTION
**Pull request by Galarzaa90**
I also had to make some minor changes to the python scripts that parse tibiawiki xml file in order for me to run them, like some absolute paths I found there.

If you prefer, I can just PR the updated database.db file

### CODE REVIEW

**Comment by BourbonCrow** [comment]
Can't launch Tibialyzer with your updated Database file says its corrupted.

```
Corrupted database Database\database.db.
Message: Specified cast is not valid.
```

**Comment by Galarzaa90** [comment]
Oh... damn.... I have no idea what could be the cause, I didn't change anything crucial in the structure of the database, and it opens fine on database browsers, python, etc

Rip pull request

**Comment by BourbonCrow** [comment]
i did notice a difference in the databases i don't know if it has to do with that since i know jack **** about sql they have different page size.. original is 4096 yours is like 1024 or whatever but that's only difference i can see---

**Comment by Galarzaa90** [comment]
@BourbonCrow That must be it, I will check it tonight

**Comment by Galarzaa90** [comment]
@BourbonCrow Nope, that didn't work, I set the page size to 4096 and no change, I compared the databases pragmas and they are the same now, getting the same error.

**Pull request closed without merging**
